require_relative 'config/environment'

desc "Loads a console"
task :console do
    Pry.start
end

desc "print out a greet"
task :hello do 
    puts "hello!!!!!!!!!!!!"
end

desc "setting up the database"
task :create_db do 
    create_table_sql = <<-SQL
        CREATE TABLE IF NOT EXISTS authors (
        id INTEGER PRIMARY KEY, 
        name TEXT);
    SQL
    DB[:conn].execute(create_table_sql)
end 

